server:
  port: 8082
spring:
  application:
    name: clients-service
  datasource:
    url: jdbc:postgresql://postgres-db:5432/client_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka
