server:
  port: 8080

spring:
  application:
    name: gateway-service

  cloud:
    discovery:
      enabled: true

    gateway:
      server:
        webflux:
          routes:
            - id: auth-service
              uri: lb://AUTH-SERVICE
              predicates:
                - Path=/api/auth/**
            - id: clients-service
              uri: lb://CLIENTS-SERVICE
              predicates:
                - Path=/api/client/**

            - id: lawyers-service
              uri: lb://LAWYERS-SERVICE
              predicates:
                - Path=/api/lawyer/**

            - id: chat-service-websocket
              uri: lb://CHAT-SERVICE
              predicates:
                - Path=/ws/**
            - id: chat-service-stomp-app
              uri: lb://CHAT-SERVICE
              predicates:
                - Path=/app/**
            - id: chat-service-stomp-topic
              uri: lb://CHAT-SERVICE
              predicates:
                - Path=/topic/**
            - id: chat-service-rest-api
              uri: lb://CHAT-SERVICE
              predicates:
                - Path=/api/chat/**
            - id: queries-service
              uri: lb://QUERIES-SERVICE
              predicates:
                - Path=/api/complaints/**
            - id: pdf-service
              uri: lb://pdf-service
              predicates:
                - Path=/api/documents/**
            - id: payment-service
              uri: lb://payment-service
              predicates:
                - Path=/api/payments/**


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/