server:
  port: 8084

spring:
  application:
    name: payment-service

  datasource:
    url: dbc:postgresql://postgres-db:5432/payments_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://discovery-service:8761/eureka

payment:
  provider: stripe

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 10000

logging:
  level:
    root: INFO
    com.legaladvisor: DEBUG
