server:
  port: 8086

spring:
  application:
    name: pdf-service

  datasource:
    url: jdbc:postgresql://postgres:5433/pdf_db
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
queries:
  base-url: http://localhost:8090


