server:
  port: 8086

spring:
  application:
    name: pdf-service

  datasource:
    url: jdbc:postgresql://postgres:5432/pdf_db
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
queries:
  base-url: http://localhost:8090


